### ISSUE TITLE
Auto-suggest chat titles with ChatGPT

### ISSUE THREAD

**Issue by Shackless** [ShipBit/slickgpt#10]
chat.openai.org has this neat feature where they let the AI set a title for your chat based on the first prompt und completion in the chat. People are bad at naming things ;) 

Condition: `if (chat.slug === chat.title)` and there is at least one question and answer in the chat

Ideas:
- either do this automatically as soon as the first answer arrived OR
- Ask the user to name the chat or offer a button to let ChatGPT pick one. Do this when the user closes a chat and above conditions are met. This could save some tokens. Bonus: Estimate how many tokens this will roughly cost. 

Technical:
it probably makes sense to set `stream: false` for this (and other) calls to the OpenAI API. This would require passing `stream` as param to the the endpoint in the [Ask API](https://github.com/ShipBit/slickgpt/blob/a8e14aa73cf83ac45e8709d76dbee32c53c2efbb/src/routes/api/ask/+server.ts) and adding a new handler in the client that receives the answer. Currently `stream` is always hardcoded to true and the handler in [ChatInput.svelte](https://github.com/ShipBit/slickgpt/blob/a8e14aa73cf83ac45e8709d76dbee32c53c2efbb/src/lib/ChatInput.svelte) always treats the answer as `EventStream`.

**Comment by Shackless** [comment]
Yeah, good idea to use the `gpt-3.5-turbo` model for this. Technically, I'd do it exactly like this - Pick the first three messages (1. context=system, 2. user=prompt, 3. assistant=answer), **append** the instructions to give a short title to the context(!) message in the current chat (preserving any context that might already be there), then query the OpenAI API with that and set `stream: false` for this request as described above.

@adaptive Do you want to give it a shot and create a PR?

**Comment by adaptive** [comment]
I could try, but I am having trouble running locally due to Firebase requirements.
