### ISSUE TITLE
Potential issue: deleted models cause frontend stuck.

### ISSUE THREAD

**Issue by xmoiduts** [ShipBit/slickgpt#104]
I'm investigating adding more models for my slickgpt fork, and found that:

If I start a new chat session with model A, then the model gets deleted in openai.ts (rather than setting the `hidden: true` flag), then the web frontend hangs and becomes unusable.

To mitigate this, I proposed a commit to switch back to the default model (gpt3.5) when the model used for the chat session is deleted.
https://github.com/xmoiduts/slick-zy-gpt/commit/68d8f0c373cd76b775e8219274c5b6b726936bff

**Comment by Shackless** [comment]
thanks for fixing it in #105
