### ISSUE TITLE
Support Azure openai api keys

### ISSUE THREAD

**Issue by anuk909** [ShipBit/slickgpt#106]

**Comment by Shackless** [comment]
This is a bit more complicated as we'd have to use the AzureOpenAIClient and it's not just "one API key" but an entire set of deployment settings, keys etc. We have this in our [Wingman AI](https://github.com/ShipBit/wingman-ai) - maybe that's suitable for you, too. I am not planning to add this in SlickGPT (but you certainly could do it in a fork).
