### ISSUE TITLE
Multiline formatting of code block is lost for several (non-supported?) languages

### ISSUE THREAD

**Issue by GrAndAG** [ShipBit/slickgpt#107]
For example, the `assembly`/`nasm`/`x86` code block lost its formatting and shown as single line.

![image](https://github.com/ShipBit/slickgpt/assets/18005116/afac141c-5f69-4d45-a8f7-a71d69d779e1)

The corresponding JSON of the response:
```json
    {
      "role": "assistant",
      "content": "Here's a simple \"Hello, World!\" program in x86 assembly language for the NASM (Netwide Assembler) assembler:\n\n```nasm\nsection .data\n    msg db 'Hello, World!', 0\n\nsection .text\n    global _start\n\n_start:\n    ; Print the message\n    mov eax, 4      ; system call number for write\n    mov ebx, 1      ; file descriptor (stdout)\n    mov ecx, msg    ; address of string to write\n    mov edx, len    ; length of string\n    int 0x80        ; invoke operating system\n\n    ; Exit the program\n    mov eax, 1      ; system call number for exit\n    xor ebx, ebx    ; return code (0)\n    int 0x80        ; invoke operating system\n\nsection .data\nlen equ $-msg    ; calculate length of string\n```\n\n...."
    },
```

Another examples:

![image](https://github.com/ShipBit/slickgpt/assets/18005116/94cd4d21-bac9-4fab-ad2c-b8139f89e877)
![image](https://github.com/ShipBit/slickgpt/assets/18005116/1768ee0c-3e70-405f-b57d-90a073721d10)

And again, a lot of `\n` in original responce are lost in code block.

**Comment by Shackless** [comment]
Yeah that's because the `highlight.js` doesn't support these languages be default. Maybe with a plugin.

**Comment by GrAndAG** [comment]
It's ok if a language is not supported and rendered without syntax highlighting. But anyway it has to be displayed "as is" at least (preserve multiline formatting).
