### ISSUE TITLE
Input is laggy on mobile or slow clients

### ISSUE THREAD

**Issue by Shackless** [ShipBit/slickgpt#13]
Reported by several users: 
Typing on mobile or slow clients leads to a noticeable delay. This is probably happening as a result of the live token cost calculation.

**Comment by joshpc** [comment]
This is happening in Firefox on a high power PC as well.

**Comment by ansysic** [comment]
Also happening on Edge on a high power PC.

**Comment by Ratcha9** [comment]
Should be fine now, we've patched this issue. The initial loading time may still be too long, though. It will be addressed with issue #8
