### ISSUE TITLE
ChatInput textarea temporarily disappearing on Edge

### ISSUE THREAD

**Issue by ansysic** [ShipBit/slickgpt#16]
When GPT is done typing the text box is disappearing completely and then reappearing.

Slow-mo capture:

https://user-images.githubusercontent.com/5899228/228207760-fd197f22-b89d-4634-a747-59a08e0fb5f4.mp4

**Comment by Shackless** [comment]
@ansysic Which browser are you using? Can't reproduce on Brave, Chrome or Safari.

**Comment by ansysic** [comment]
Edge.

After further inspection this is the explanation I came up with:
It happens because Edge allows you to scroll back to the top of the page when streaming a GPT reply while at lease Safari prevents you from doing so.

**Comment by Shackless** [comment]
Okay thanks. I think this is minor and very low prio.

**Comment by ansysic** [comment]
Agree!
