### ISSUE TITLE
Ability to set default Model

### ISSUE THREAD

**Issue by Arro** [ShipBit/slickgpt#25]
It would be nice to not have to go in and change from `3.5-turbo` to `4` every time I make a new thread.

(Great app btw!)

**Comment by Shackless** [comment]
See https://github.com/ShipBit/slickgpt/issues/26#issuecomment-1491072558 for a temp workaround

**Comment by Shackless** [comment]
You'll find a new button next time you change the model in a chat: 

<img width="322" alt="image" src="https://user-images.githubusercontent.com/306996/229103629-e81e4324-ef13-41a9-b7c2-42c7d9eeed3d.png">
