### ISSUE TITLE
Integrate Moderation API

### ISSUE THREAD

**Issue by Shackless** [ShipBit/slickgpt#4]
Quote OpenAI: 

_The [moderation](https://platform.openai.com/docs/api-reference/moderations) endpoint is a tool you can use to check whether content complies with OpenAI's [usage policies](https://openai.com/policies/usage-policies). Developers can thus identify content that our usage policies prohibits and take action, for instance by filtering it._

See [OpenAI Docs](https://platform.openai.com/docs/guides/moderation/overview)

This endpoint is free and it would be nice if SlickGPT would integrate this API.

**Comment by th8m0z** [comment]
I would second this idea and could also work on implementing it, if this is okay with the maintainers.

**Comment by Shackless** [comment]
You have our blessing!

**Comment by Shackless** [comment]
added in #88 - I forgot to close the issue
