### ISSUE TITLE
Can't select and copy text for SlickGpt text frames

### ISSUE THREAD

**Issue by Vadiml1024** [ShipBit/slickgpt#49]
I'm trying to select text, copy it and pas to my editor....
It is impossible for some reason... The selection seems not to work.
It is the same for the frame where i enter my text and for frames with my previous input, GPT output too, and context editing frame too,

I'm running Chromium Version 111.0.5563.146 (Official Build) snap (64-bit)
Under Ubuntu 18.04

**Comment by Vadiml1024** [comment]
After some more testing:  No problem under Firefox. I can select thext and copy it.

**Comment by Shackless** [comment]
@Vadiml1024 That's weird. Could you try to inspect the page in your environment? My guess would be that it's some kind of overlay that is not rendered correctly and "eats up" your mouse events. I can't easily test in that particular setup though.

**Comment by Vadiml1024** [comment]
@Shackless Will do... However, maybe a COPY button in text frames that copies the text to clipboard will useful IMHO,
 especially in similar situations.

**Comment by Vadiml1024** [comment]
> @Vadiml1024 That's weird. Could you try to inspect the page in your environment? My guess would be that it's some kind of overlay that is not rendered correctly and "eats up" your mouse events. I can't easily test in that particular setup though.

You're very probably right. I've just tested on another machine under Chromium too but with another set of Chrome extensions
and all works perfectly well. I'll try this evening to find the extension which wreaks havoc with text selection, but as I said before COPY button will be a life saver here

**Comment by Shackless** [comment]
Hmm okay, let's try to find out which extension is causing that and if we can work around this issue. I'd rather not clutter the messages toolbar more. As a quick workaround for your setup try this: 
Tap the "Edit message" button. This will copy the text of the message to the ChatInput. Try to copy from there, then cancel the edit operation.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/306996/235622957-8861f449-0c25-4b73-b664-842a4f42d0c0.png">

<img width="1798" alt="image" src="https://user-images.githubusercontent.com/306996/235623140-37d16c3d-820a-4e8a-8eba-2ee66b604647.png">

**Comment by Shackless** [comment]
Closed due to inactivity. Feel free to reopen if it still bothers you.
