### ISSUE TITLE
FIREFOX: Height attribute on chatInput textarea compressing below 1 row size

### ISSUE THREAD

**Issue by ucffool** [ShipBit/slickgpt#57]
I have not been able to find what's applying a `height: 20px` inline on the textarea, but it's breaking things. 
**Firefox**, latest, mobile and desktop.

**Expectation**
![no height css](https://i.imgur.com/L7dO8sh.jpg)

**Reality**
![20px height css](https://i.imgur.com/Y0q3igD.jpg)

In Chrome it seems to work fine, and a height of 42px is assigned (desktop), so I'm guessing there is some js or post processor that I don't know about doing it, so I'm posting here.

**Comment by Shackless** [comment]
Thanks, fixed
