### ISSUE TITLE
Self-hosted, behind nginx proxy: CORS and JSON errors

### ISSUE THREAD

**Issue by bpawel-bclub** [ShipBit/slickgpt#65]
Hi, I managed to run slickgpt on my own server, using @sveltejs/adapter-node, and behind nginx proxy with Let's Encrypt SSL.

When I try to use SuggestTitleModal.svelte I get some errors. They only show when I connect via my domain. If going through IP:port directly, all works fine.

JSON:

```
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data SuggestTitleModal.svelte:573:2
    handleSuggestTitle SuggestTitleModal.svelte:573
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    listen index.mjs:463
    listen_dev index.mjs:2325
    mount SuggestTitleModal.svelte:122
    mount SuggestTitleModal.svelte:459
    m svelte-hooks.js:291
    mount_component index.mjs:2097
    mount @skeletonlabs_skeleton.js:25390
    mount @skeletonlabs_skeleton.js:26472
    mount @skeletonlabs_skeleton.js:25276
    update @skeletonlabs_skeleton.js:26709
    update index.mjs:1347
    flush index.mjs:1307
    (Async: promise callback)
    schedule_update index.mjs:1258
    make_dirty index.mjs:2133
    ctx index.mjs:2171
    instance32 @skeletonlabs_skeleton.js:26759
    set index.mjs:34
    update index.mjs:42
    trigger stores.js:10
    showModalComponent shared.ts:129
    handleEditTitle Toolbar.svelte:13
    (Async: EventListener.handleEvent)
    listen index.mjs:463
    listen_dev index.mjs:2325
    mount Toolbar.svelte:80
    mount Toolbar.svelte:203
    m svelte-hooks.js:291
    mount_component index.mjs:2097
    mount +page.svelte:132
    mount +page.svelte:1315
    m svelte-hooks.js:291
    mount_component index.mjs:2097
    update root.svelte:292
    update_slot_base index.mjs:100
    update +layout.svelte:89
    update_slot_base index.mjs:100
    update @skeletonlabs_skeleton.js:5920
    update index.mjs:1347
    flush index.mjs:1307
    (Async: promise callback)
    schedule_update index.mjs:1258
    make_dirty index.mjs:2133
    ctx index.mjs:2171
    $$set root.svelte:619
    get proxy.js:83
    $set index.mjs:2272
    key proxy.js:46
    navigate client.js:1096
    InterpretGeneratorResume self-hosted:1455
    AsyncFunctionNext self-hosted:852
    (Async: async)
    _start_router client.js:1569
    (Async: EventListener.handleEvent)
    _start_router client.js:1485
    start start.js:27
    <anonymous> (index):30
    (Async: promise callback)
    <anonymous> (index):29
```

also in GET:

` NS_ERROR_WEBSOCKET_CONNECTION_REFUSED `

and in POST:

```
Status
403
Forbidden
VersionHTTP/2
Transferred405 B (46 B size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest
DNS ResolutionSystem
````

**Comment by Shackless** [comment]
This sounds like a webserver / domain-related problem. I'm no expert on this topic but sounds like you have to enable CORS or whitelist the OpenAI API URL that is being called by the SuggestTitleModal in your webserver.

**Comment by bpawel-bclub** [comment]
hmm, the thing is that it generates responses so I think the API calls are working in principle, but I'm no expert either. Here is what SlickGPT (connected to ChatGPT-4) answered 😎:

> The nginx configuration you provided looks fine, and the errors you're encountering are unrelated to the nginx configuration itself.
> The error NS_ERROR_WEBSOCKET_CONNECTION_REFUSED indicates that there is an issue establishing a WebSocket connection. This could be due to a misconfiguration in your Svelte application or an issue with the server-side WebSocket implementation. You should check your Svelte application's WebSocket code and ensure that the server is properly configured to handle WebSocket connections.
> The error 403 Forbidden suggests that the server is refusing to process the POST request. There could be various reasons for this, such as incorrect permissions or missing CSRF tokens. You should inspect your server-side code and check for any logic that might be blocking the request. You may also want to check your server logs for more detailed error information.
> In summary, the nginx configuration appears to be correct, and the errors you're experiencing are likely related to your Svelte application or server-side code. Review and debug your code to identify and resolve any issues causing these errors.

**Comment by Merkie** [comment]
Hey [bpawel-bclub](https://github.com/bpawel-bclub), have you set the origin environment variable? You need to set that up with the domain you're using so the node adapter knows what origin people are hitting your site from. Read here: https://kit.svelte.dev/docs/adapter-node#environment-variables
