### ISSUE TITLE
I can't access the app from my private vps

### ISSUE THREAD

**Issue by d4rkc0de** [ShipBit/slickgpt#66]
The app works fine locally, but when I run it on my server, and then I access vps-ip-address:5173/ the app doesn't load at all.

I'm no expert in node or npm, what I am missing here ?

**Comment by Shackless** [comment]
Try building the app with npm run build, then throw the generated /dist (or /build, can’t recall) directory on your web server. Then it should run with the default port 80 which you don’t have to put in the address manually. 

Sounds like you’re trying to start the dev server on your host or you just pushed the source code and didn’t start it at all.

**Comment by d4rkc0de** [comment]
I build the app with npm run build, but the generated files were under this path (weird?) .svelte-kit/output/server

Then I tried to run the app using "node index.js" inside .svelte-kit/output/server

It didn't show any errors, but I wasn't able to access the app using multiple ports ( 80, 5173, 4173, 8080 ...)

**Comment by Shackless** [comment]
Well, running it with node does not start or expose a webserver. You need one that does that for you. If you run `npm run dev`, then Vite will do that for you. I'll close this issue as it's not related to SlickGPT but a general question on how to host and run Svelte applications.
