### ISSUE TITLE
[Feature] Fuzzy search all messages in all chats

### ISSUE THREAD

**Issue by Merkie** [ShipBit/slickgpt#74]
Title is self-explanatory. I wish ChatGPT had this, so I'll add it to this project. But there should be a command palette or a search bar that lets you search through all your chats, this would be very useful. I'll work on an initial PR.

**Comment by Shackless** [comment]
Great idea! I'd also be fine with using a 3rd party lib for the command palette if it's good and has a lightweight payload. I bookmarked https://github.com/rohitpotato/svelte-command-palette a while ago but haven't tried it yet. I'm sure there are also other JS libs that do the same thing.

**Comment by th8m0z** [comment]
If nobody is working on this so far, I'd love to get started on the feature

**Comment by th8m0z** [comment]
Just submitted a first [PR](https://github.com/ShipBit/slickgpt/pull/80)
