### ISSUE TITLE
GPT-4-vision-preview support

### ISSUE THREAD

**Issue by jeppevinkel** [ShipBit/slickgpt#77]
Is there any plans currently to support the new GPT-4-vision model in the future for uploading images in chats?

**Comment by Shackless** [comment]
I currently don't have much time to work on SlickGPT but I'd gladly take a PR for this. Skeleton UI already has fileupload controls (button/dialog) and dropzone, so this shouldn't be that hard to do.

**Comment by Anajrim01** [comment]
wip
