### ISSUE TITLE
Long code-formatted text won't wrap during generation

### ISSUE THREAD

**Issue by xmoiduts** [ShipBit/slickgpt#82]
In generating code-formatted long texts that do contain new lines, the response bubble won't wrap and exceeds the screen. Image below:
![image](https://github.com/ShipBit/slickgpt/assets/16047865/22bba24f-e8df-41ee-9614-c58e5274f2ca)

The properly wrapped format is demonstrated after generation is complete. Example:
![image](https://github.com/ShipBit/slickgpt/assets/16047865/f9cae433-0c9e-4bc4-bead-6385997dccc2)

**Comment by EnnioEvo** [comment]
Same problem, it makes the whole answer not readable until the generation is completed

**Comment by Shackless** [comment]
This should be fixed by #92
