### ISSUE TITLE
Automagically set titles at appropriate time to suit mobile navigation and browser behaviors.

### ISSUE THREAD

**Issue by xmoiduts** [ShipBit/slickgpt#90]
When `automagically set titles` is enabled, SlickGPT sets the title at quitting the session by clicking [X] on the top-right of the screen. On mobile devices, it may not be compatible with gesture navigations.

android + chrome + swipe-to-return = swipe to switch to the previous "sessions" view, without triggering auto-set-titles functionality.

It would be good to align with ChatGPT which sets titles upon the first response.

**Comment by Anajrim01** [comment]
I can pr this.

**Comment by Anajrim01** [comment]
@Shackless this issue can now be closed.
